services:
  fastapi:
    build:
      context: ./backend
      dockerfile: fastapi/Dockerfile
    volumes:
      - ./backend/fastapi:/app
      - ./backend/common:/app/common
    env_file:
      - ./.env
      - ./backend/fastapi/.env
    network_mode: host

  flask:
    build:
      context: ./backend
      dockerfile: flask/Dockerfile
    volumes:
      - ./backend/flask:/app
      - ./backend/common:/app/common
    env_file:
      - ./.env
      - ./backend/flask/.env
    network_mode: host
