services:
  django-web:
    build: ./backend/django
    volumes:
      - ./backend/django:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      - ./backend/django/.env
    network_mode: host
