services:
  fastapi:
    build:
      context: ./backend
      dockerfile: fastapi/Dockerfile
    volumes:
      - ./backend/fastapi:/app
      - ./backend/common:/app/common
    env_file:
      - ./.env
      - ./backend/fastapi/.env
    network_mode: host
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  flask:
    build:
      context: ./backend
      dockerfile: flask/Dockerfile
    volumes:
      - ./backend/flask:/app
      - ./backend/common:/app/common
    env_file:
      - ./.env
      - ./backend/flask/.env
    network_mode: host
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
