services:
  django-web:
    build: ./backend/django
    volumes:
      - ./backend/django:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      - ./backend/django/.env
    network_mode: host
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 5s
