spec:
  name: life-manager
  region: fra
  services:
    - name: fastapi
      source_dir: backend/fastapi
      dockerfile_path: backend/fastapi/Dockerfile
      http_port: 8001
      instance_size_slug: basic-xxs
      instance_count: 1
      health_check:
        http_path: /healthcheck
        initial_delay_seconds: 10
      envs:
        - key: PYTHONUNBUFFERED
          value: '1'
        - key: PORT
          value: '8001'
    - name: flask
      source_dir: backend/flask
      dockerfile_path: backend/flask/Dockerfile
      http_port: 8000
      instance_size_slug: basic-xxs
      instance_count: 1
      health_check:
        http_path: /healthcheck
        initial_delay_seconds: 10
      envs:
        - key: PYTHONUNBUFFERED
          value: '1'
        - key: PORT
          value: '8000'
  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
    - rule: CPU_UTILIZATION
      value: 80
    - rule: MEM_UTILIZATION
      value: 80
